version: '3.5'
services:
  vprodb:
    build:
      context: ./Docker-files/db
    image: dalabehera/vprofiledb
    container_name: vprodb  # Corrected typo
    ports:
      - "3306:3306"
    volumes:
      - vprodbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Heypukun.98  # Corrected variable name

  vrpocache01:
    image: memcached
    ports:  # Changed from 'port' to 'ports'
      - "11211:11211"

  vpromq01:
    image: rabbitmq
    ports:
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  vproapp:
    build:
      context: ./Docker-files/app
    image: dalabehera/vprofileapp
    container_name: vproapp  # Corrected typo
    ports:
      - "8080:8080"
    volumes:
      - vproappdata:/usr/local/tomcat/webapps

  vproweb:
    build:
      context: ./Docker-files/web
    image: dalabehera/vprofileweb
    container_name: vproweb  # Corrected typo
    ports:
      - "80:80"

volumes:
  vprodbdata: {}
  vproappdata: {}
